services:
  chatflow-db:
    image: postgres:alpine
    container_name: chatflow-db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - chatflow_data:/var/lib/postgresql/data
  adminer:
    container_name: chatflow-adminer
    image: adminer
    restart: always
    depends_on:
      - chatflow-db
    ports:
      - "8080:8080"
  chatflow-redis:
    image: redis:alpine
    container_name: chatflow-session
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - chatflow_session:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} --appendonly yes
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin
    links:
      - chatflow-redis
    ports:
      - "8081:80"
    environment:
      - REDIS_1_HOST=${REDIS_HOST_DOCKER}
      - REDIS_1_NAME=${REDIS_NAME}
      - REDIS_1_PORT=${REDIS_PORT}
      - REDIS_1_AUTH=${REDIS_PASSWORD}
volumes:
  chatflow_data:
    driver: local
  chatflow_session:
    driver: local
